descriptions = {
  'categories/apparel/boardshorts' => '<p>Boardshorts built for kitesurfers, windsurfers, SUP paddlers, and anyone spending serious time in and around the water — not just the beach bar.</p><p>Whether you need a quick-dry stretch short for a kite session or a longer cut for paddling comfort, the right boardshort makes a genuine difference when you\'re active. Flat-waist construction, secure pockets, and four-way stretch fabrics mean these move with you, not against you.</p><ul><li><strong>Quick-dry fabrics:</strong> back in the water or at the cafe within minutes</li><li><strong>Secure pockets:</strong> zip or velcro closures keep your key and card in place</li><li><strong>Stretch construction:</strong> four-way stretch for kicking, paddling, and squatting on the board</li></ul><p>Grab a pair from ION or Duotone and spend less time adjusting your shorts and more time riding.</p>',

  'categories/apparel/cap' => '<p>Sun protection starts at the top — a quality water sports cap keeps harmful UV off your face and eyes during long sessions on the water.</p><p>Flat-water SUP sessions, downwinder kite runs, and offshore windsurfing can mean four or more hours of direct sun exposure. A cap with UPF fabric, a wide brim, and a chin retention cord stays put even in strong wind — unlike standard baseball caps that end up overboard at the worst moment.</p><ul><li><strong>Chin retention cord:</strong> keeps your cap on in gusty conditions</li><li><strong>UPF-rated fabric:</strong> blocks 98% or more of UV radiation</li><li><strong>Fast-drying:</strong> comfortable whether wet or dry throughout the session</li></ul><p>Pair with a lycra top from ION for full-coverage sun protection on the water.</p>',

  'categories/apparel/coats' => '<p>A good surf jacket or coast coat is the piece of kit that makes shoulder-season sessions actually enjoyable rather than just endurable.</p><p>Dawn patrol kite sessions, post-surf beach walks, and early-morning SUP outings all demand something wind-resistant and packable that you can peel off once the sun hits. Waterproof outer shells, fleece linings, and packable construction mean you get real warmth without the bulk of a full wetsuit top when conditions don\'t quite justify neoprene.</p><ul><li><strong>Waterproof shell:</strong> blocks wind and light rain without the weight</li><li><strong>Packable design:</strong> stuffs into its own pocket for easy transport</li><li><strong>Versatile cut:</strong> works over a wetsuit or as a standalone layer</li></ul><p>ION and Duotone both offer excellent technical outerwear designed specifically for watersport athletes.</p>',

  'categories/apparel/lycra' => '<p>Lycra rashguards are the unsung workhorse of every serious surfer, kitesurfer, and SUP paddler\'s kit bag — light, fast-drying, and effective against both sun and abrasion.</p><p>A rashguard rated UPF 50+ blocks 98% of UV radiation, so you can spend a full day on the water without loading up on sunscreen. Long-sleeve options also protect against board rash, harness chafing, and jellyfish contact. Flatlock stitching keeps seams smooth where they sit under a harness or wetsuit.</p><ul><li><strong>UPF 50+ protection:</strong> full-day sun coverage without sunscreen</li><li><strong>Flatlock seams:</strong> no chafing under a kite harness or wetsuit</li><li><strong>Four-way stretch:</strong> unrestricted movement for paddling and riding</li></ul><p>ION makes some of the most durable rashguards in the game — built for daily use, not occasional beach trips.</p>',

  'categories/apparel/nylon-surf-shirt' => '<p>Nylon surf shirts combine the coverage of a rashguard with a more structured, athletic fit — popular with kitesurfers and windsurfers who want sun protection without the clingy compression feel of pure lycra.</p><p>The woven nylon construction dries faster than cotton, resists snags from kite lines and board rails, and holds its shape wash after wash. A longer back hem stays tucked into boardshorts or a harness during dynamic sessions, and the fabric breathes well in warm tropical and Mediterranean conditions.</p><ul><li><strong>Woven nylon fabric:</strong> snag-resistant and faster drying than cotton</li><li><strong>Extended back hem:</strong> stays tucked under a harness through the session</li><li><strong>Sun protection:</strong> UPF-rated construction for full-day coverage</li></ul><p>Ideal for kitesurfers who want a clean look on and off the water without carrying a separate top.</p>',

  'categories/apparel/ponchos' => '<p>A surf poncho — or changing robe — is quite possibly the most underrated piece of kit you\'ll ever buy, until the first time you change out of a wetsuit in a car park in February.</p><p>The thick towelling lining dries you off and keeps you warm simultaneously, while the generous cut gives enough room to change underneath with full privacy. Oversized hoods, kangaroo pockets, and mid-thigh length make these practical from the beach to the coffee shop without needing a change of clothes. Microfibre versions pack lighter and dry faster for travel.</p><ul><li><strong>Double-layered towelling:</strong> dries and insulates at the same time</li><li><strong>Full-coverage cut:</strong> easy to change underneath in public</li><li><strong>Deep kangaroo pocket:</strong> keeps your phone and keys warm and dry</li></ul><p>ION ponchos are a favourite across kite and surf beaches — built to last a serious number of seasons.</p>',

  'categories/apparel/sun-protection' => '<p>Proper sun protection clothing is essential for anyone spending regular time on the water — reflected UV from the surface doubles your exposure compared to dry land.</p><p>UPF 50+ rated garments block 98% of UV radiation across every surface they cover, offering more reliable and longer-lasting protection than sunscreen alone. Full-length leggings, long-sleeve tops, and sun hoodies are now standard kit for kitesurfers, SUP paddlers, and windsurfers across tropical and summer destinations where sun exposure is highest.</p><ul><li><strong>UPF 50+ rating:</strong> laboratory certified UV blocking across all covered areas</li><li><strong>Lightweight construction:</strong> cool and comfortable in warm water temperatures</li><li><strong>Full coverage options:</strong> leggings, tops, hoods, and suits available</li></ul><p>ION offers a comprehensive sun protection range designed for the demands of active watersports — not just beach lounging.</p>',

  'categories/apparel/tops' => '<p>Surf tops and casual beach tops bridge the gap between technical kit and everyday wear — the kind of piece you reach for from the beach carpark to the session and straight to the cafe without thinking twice.</p><p>Whether it\'s a technical polo for the journey, a relaxed organic cotton tee, or a technical loose-fit top for light paddling days, having the right top makes transitions smoother. Look for quick-dry fabrics, UV-aware construction, and a fit that works whether you\'re rigging kite lines or ordering coffee.</p><ul><li><strong>Quick-dry fabrics:</strong> comfortable wet or dry through the full day</li><li><strong>Relaxed athletic fit:</strong> moves freely without restricting paddling or rigging</li><li><strong>Versatile style:</strong> presentable enough beyond the beach</li></ul><p>Duotone and ION both offer quality beach and technical tops that wear well across surf and everyday use.</p>',

  'categories/e-foil/e-foil-spare-parts' => '<p>Keep your electric foil running at full power with genuine e-foil spare parts — batteries, propellers, masts, wings, and electronics sourced from leading manufacturers.</p><p>E-foils are sophisticated machines and genuine spare parts make the difference between a short delay and an expensive repair. Whether you\'ve clipped a sandbar and damaged your propeller, need a replacement battery to double your session time, or are upgrading your mast length for a different riding style, having access to the right components matters. Electronics including ESCs, motor components, and remote control systems are particularly critical to source correctly.</p><ul><li><strong>Battery packs:</strong> replacement and additional batteries to extend session time</li><li><strong>Propellers and guards:</strong> replacement props after impacts or upgrades</li><li><strong>Masts and wings:</strong> alloy and carbon mast sections, front and rear wings</li></ul><p>We stock spare parts for major e-foil brands so you spend less time waiting and more time flying above the water.</p>',

  'categories/kitesurfing/kite-accessories' => '<p>The right kite accessories keep your session running smoothly — from launch to landing and every moment on the water in between.</p><p>Kitesurfing is a technical sport and the supporting accessories matter as much as the kite and board themselves. A failing chicken loop mid-session, a burst pump at the beach, or a snapped leash are all preventable with quality kit. This category covers everything that supports your kite setup: pumps, safety systems, bar components, pads, and spare parts.</p><ul><li><strong>Safety systems:</strong> leashes and chicken loops from Duotone, Cabrinha, and ION</li><li><strong>Inflation tools:</strong> hand pumps and electric pump options</li><li><strong>Bar components:</strong> trim systems, pads, and replacement hardware</li></ul><p>Browse accessories from Duotone, Cabrinha, North, and F-One — the brands that kite the world\'s best spots trust.</p>',

  'categories/kitesurfing/kite-accessories/chicken-loop' => '<p>The chicken loop is your direct connection to the kite bar\'s quick-release system — it\'s one of the most safety-critical components in your entire kite setup.</p><p>A worn or incompatible chicken loop can prevent a clean emergency release when you need it most. Modern chicken loops come with a finger (chicken finger) that locks the loop onto your hook, preventing accidental release during powered riding. When replacing, always match the loop to your bar system — Duotone, Cabrinha, North, and F-One all have specific fitments that are not universally interchangeable.</p><ul><li><strong>Quick-release compatible:</strong> designed to work cleanly with your bar\'s safety system</li><li><strong>Chicken finger included:</strong> prevents unintentional unhooking during powered riding</li><li><strong>Brand-specific fitments:</strong> Duotone, Cabrinha, North, and F-One options available</li></ul><p>Replace your chicken loop at the first sign of wear — it\'s an inexpensive part that protects an expensive investment.</p>',

  'categories/kitesurfing/kite-accessories/kite-pads' => '<p>Kite bar pads and trim systems improve comfort and control during long sessions — a quality pad reduces hand fatigue and keeps your bar positioned exactly where you want it.</p><p>Bar pads sit between your hands and the bar, softening the impact of chop transmission through the lines and giving you a more natural grip position. Trim systems — the strap or cleat that adjusts your depower — should move smoothly under load and hold their position reliably. Worn trim systems that slip under load affect kite performance directly.</p><ul><li><strong>Bar pads:</strong> neoprene or foam pads to reduce grip fatigue on longer sessions</li><li><strong>Trim system:</strong> depower cleats and straps for fine kite tuning</li><li><strong>Bar end protection:</strong> end caps and guards to protect bar tips</li></ul><p>Compatible pads and trim parts available for Duotone, Cabrinha, North, and F-One bar systems.</p>',

  'categories/kitesurfing/kite-accessories/leash' => '<p>A kite leash is your last line of defence between a powered, depowered kite and losing it entirely — choosing the right leash for your riding style matters.</p><p>Safety leashes connect your harness to the kite\'s fifth line or safety system, ensuring that when you trigger the quick-release, the kite flags out and can be retrieved. Wrist leashes are popular in waves and for riders who want a shorter, cleaner attachment. The leash should be long enough to allow full movement but short enough to keep the kite manageable after release.</p><ul><li><strong>Harness leashes:</strong> standard attachment for most riding styles and conditions</li><li><strong>Wrist leashes:</strong> preferred in surf and wave conditions for quick self-rescue</li><li><strong>Coiled design:</strong> prevents trailing lines and tangles during riding</li></ul><p>ION, Duotone, and Cabrinha all offer well-engineered leash systems — replace yours every season for reliable safety performance.</p>',

  'categories/kitesurfing/kite-accessories/pump' => '<p>A reliable kite pump is one of those pieces of kit you genuinely can\'t afford to cheap out on — a slow or broken pump wastes session time and wears you out before you even hit the water.</p><p>Modern double-action hand pumps inflate on both the push and pull stroke, cutting inflation time significantly compared to single-action pumps. High-pressure hose attachments allow you to top off a kite to the correct PSI for the conditions. Electric pumps take it further, inflating a full kite without any manual effort — particularly useful in hot, humid conditions or when running multiple kites.</p><ul><li><strong>Double-action hand pumps:</strong> inflate on push and pull for twice the efficiency</li><li><strong>High-pressure gauge:</strong> ensures correct PSI for kite longevity</li><li><strong>Electric pump options:</strong> battery-powered inflation for zero-effort setup</li></ul><p>Duotone and Cabrinha pumps are designed specifically for their kite valve systems for a guaranteed leak-free connection.</p>',

  'categories/kitesurfing/kite-accessories/spare-parts' => '<p>A well-stocked kite spare parts kit can turn a session-ending problem into a five-minute fix — bladders, struts, valves, and leading edge sections are all field-repairable with the right parts.</p><p>The most common failures are bladder punctures in struts and leading edges, valve failures, and tip bridle wear. Carrying a set of spare bladders for your kite sizes, a valve repair kit, and the manufacturer\'s repair tape means you can handle most issues at the beach. Leading edge and strut repairs are also achievable with the right two-part adhesive and a spare section.</p><ul><li><strong>Bladders:</strong> strut and leading edge replacement bladders for your specific kite</li><li><strong>Valves:</strong> Duotone, Cabrinha, and North valve replacement kits</li><li><strong>Repair materials:</strong> manufacturer-specific dacron patches, adhesives, and tape</li></ul><p>Stock up on the essentials for your kite brand — a small spare parts kit pays for itself on the first trip it saves.</p>',

  'categories/kitesurfing/kite-foil' => '<p>Kite hydrofoiling has redefined what\'s possible in light wind kitesurfing — flying above the water on a foil opens up sessions in conditions that would otherwise leave you onshore.</p><p>A kite foil system consists of a board, mast, fuselage, front wing, and stabiliser working together to generate lift. Once you\'re up and foiling, the reduced drag means you can ride in winds as light as 8–10 knots. Kite foiling also changes the riding style completely — slower, more flowing turns and a sensation closer to flight than surfing.</p><ul><li><strong>Front wing:</strong> the primary lift surface — larger wings for lighter winds</li><li><strong>Mast length:</strong> longer masts for choppier water, shorter for more direct feel</li><li><strong>Fuselage:</strong> connects front wing, rear stabiliser, and mast</li></ul><p>Duotone, Cabrinha, F-One, and Naish all produce refined kite foil systems for beginners through to race-level competitors.</p>',

  'categories/kitesurfing/kite-foil/foil-mast' => '<p>The foil mast is the vertical strut that connects your board to the foil assembly — mast length and material directly affect how your foil handles in every condition.</p><p>Shorter masts (60–70cm) keep you closer to the water surface and give a more direct, responsive feel — popular with wave foiling and beginners who prefer a lower risk of breaching. Longer masts (80–100cm+) provide more clearance in choppy conditions and allow for higher speeds without breach risk, favoured by race and advanced freeride riders. Carbon construction saves weight and increases stiffness compared to aluminium.</p><ul><li><strong>Aluminium masts:</strong> durable, affordable, and suitable for learning and recreational foiling</li><li><strong>Carbon masts:</strong> lighter and stiffer for performance-oriented riding</li><li><strong>Multiple lengths:</strong> 60cm to 100cm+ to match your riding style and conditions</li></ul><p>F-One, Duotone, and Naish mast systems offer broad compatibility across their foil ranges.</p>',

  'categories/kitesurfing/kite-foil/kite-foil-parts' => '<p>Fine-tune your kite foil performance with the right components — front wings, rear stabilisers, fuselages, and shims that adjust lift, speed, and turning characteristics.</p><p>Modular foil systems allow you to swap front wings for different conditions: a high-aspect race wing for speed and efficiency, a larger low-aspect wing for light winds and beginners, or a dedicated wave wing for carving turns in surf. Shims adjust the angle of the rear stabiliser to tune pitch feel and direct/indirect handling. Fuselage length affects stability — shorter fuselages are more agile, longer ones more forgiving.</p><ul><li><strong>Front wings:</strong> different aspect ratios for speed, light wind, or wave riding</li><li><strong>Rear stabilisers:</strong> tune pitch stability and turning radius</li><li><strong>Fuselages and shims:</strong> adjust geometry for different riding styles</li></ul><p>Duotone, Cabrinha, F-One, and Naish all run modular systems — mix and match within the range for your ideal foil setup.</p>',

  'categories/kitesurfing/kite-foil/kitefoil-board' => '<p>A kitefoil board is a specialised short, narrow board designed to get you onto the foil quickly and stay there — built for one job and built to do it well.</p><p>Foil boards are typically 120–140cm long and much narrower than a twin tip, with a foil track or tuttle box positioned for balanced lift. Learning boards are more stable with wider tails and forgiving shapes, while advanced boards are small and directional, designed to be discarded at speed once you\'re fully committed to the foil. Strap setups, pad positions, and mast track placement all vary between manufacturers.</p><ul><li><strong>Learning boards:</strong> wider, more stable shapes to help beginners get foiling faster</li><li><strong>Performance boards:</strong> compact and light for advanced speed and carving</li><li><strong>Compatible hardware:</strong> tuttle or deep-tuttle box systems from major foil brands</li></ul><p>Duotone, Cabrinha, and F-One offer dedicated kitefoil boards to match their foil systems precisely.</p>',

  'categories/kitesurfing/kiteboards/kite-foil-board' => '<p>Kitefoil boards built for the full spectrum of foiling — from first flights on twin tips through to high-performance directional shapes for advanced riders.</p><p>The distinction between a dedicated foil board and a foil-converted twin tip matters. Purpose-built foil boards are optimised in stiffness, flex, and track placement for efficient foil riding from the first pump. Twin tips adapted for foiling can work but are a compromise. For riders progressing into foiling, a dedicated board with a strong centre box and reinforced deck pays off quickly in comfort and progression rate.</p><ul><li><strong>Twin tip foil boards:</strong> accessible entry point, familiar stance for twin tip riders</li><li><strong>Directional foil boards:</strong> surf-style shapes for advanced wave and downwind foiling</li><li><strong>Stiff construction:</strong> carbon and fibre layups to minimise flex under foil loads</li></ul><p>F-One, Duotone, and Naish build dedicated foil boards that work seamlessly with their respective foil systems.</p>',

  'categories/kitesurfing/kiteboards/kitesurf-board' => '<p>Directional kitesurf boards bring the experience of surfing into the world of kitesurfing — riding waves with a kite changes everything about how a wave feels.</p><p>A kitesurf directional — sometimes called a surfboard or strapless board — is shaped to generate its own speed through a wave, allowing riders to downsize their kite and use the wave\'s energy for turns and progression. Shapes range from high-volume beginners\' boards with plenty of paddle-style glide through to narrow, high-performance shortboards for advanced surf shredding in solid conditions.</p><ul><li><strong>High-volume shapes:</strong> forgiving and fast to learn on in cross-shore conditions</li><li><strong>Performance shortboards:</strong> narrow and responsive for progressive wave riding</li><li><strong>Strapless compatible:</strong> clean deck construction for freestyle strapless tricks</li></ul><p>Duotone, Cabrinha, and F-One all produce wave-oriented kitesurf directionals designed to match their kite ranges in surf.</p>',

  'categories/kitesurfing/kiteboards' => '<p>The right kiteboard transforms your riding — whether you\'re learning your first water start, lapping a flat-water lagoon, or carving waves strapless on a directional.</p><p>Kiteboards span a wide range: twin tips for versatile riding in both directions, directional surfboards for waves, foil boards for flying above the surface, and everything in between. Board size, flex, shape, and rocker all interact with your kite choice, your body weight, and the conditions you ride most. Choosing the right board for your stage and style makes progression noticeably faster.</p><ul><li><strong>Twin tips:</strong> ride in both directions, ideal for flat water and learning</li><li><strong>Directionals:</strong> surf-style boards for waves and downwind riding</li><li><strong>Foil boards:</strong> specialised shapes for kite hydrofoiling</li></ul><p>Browse kiteboards from Duotone, Cabrinha, North, and F-One — brands that develop their boards and kites as matched systems.</p>',

  'categories/kitesurfing/kite-harnesses' => '<p>Your kite harness is the interface between your body and the kite\'s power — comfort, fit, and support directly affect how long and how well you ride.</p><p>Waist harnesses sit at the hips and give maximum freedom of movement — the default choice for most freestyle and freeride riders. Seat harnesses distribute the load across hips and thighs, making them more supportive for beginners, heavier riders, or anyone who prefers reduced lower back strain. Hardshell back supports are an option for riders with existing back issues. Every harness should be sized to fit snugly without riding up during riding.</p><ul><li><strong>Waist harnesses:</strong> maximum freedom of movement for freestyle and freeride</li><li><strong>Seat harnesses:</strong> more supportive load distribution for beginners or longer sessions</li><li><strong>Spreader bar compatibility:</strong> check fitment with your specific bar system</li></ul><p>ION, Duotone, and Cabrinha harnesses are engineered for kitesurfing specifically — not adapted from windsurfing or wakeboarding designs.</p>',

  'categories/kitesurfing/kites' => '<p>The kite is the engine of the whole system — choosing the right one for your skill level, body weight, and local conditions defines your entire kitesurfing experience.</p><p>Leading Edge Inflatable (LEI) kites are the standard across freeride, wave, and freestyle riding: they relaunch from the water, pack down small, and cover a broad wind range. Foil kites offer maximum efficiency and light wind performance but require more experience to manage on the water. Within LEI kites, delta-bow shapes dominate modern riding for their wide depower range and accessible handling.</p><ul><li><strong>Freeride kites:</strong> wide wind range and forgiving handling for all-round riding</li><li><strong>Wave kites:</strong> fast, responsive turning with smaller sizes for wave-focused riding</li><li><strong>Foil kites:</strong> maximum light wind performance for experienced riders</li></ul><p>We stock kites from Duotone, Cabrinha, North, F-One, and Naish — all the major brands in one place.</p>',

  'categories/kitesurfing/kites/parawings' => '<p>Parawings — ram-air soft kites designed for hand-held use — have opened up entirely new disciplines on water, land, and snow without the complexity of a traditional kite bar system.</p><p>The parawing concept, popularised by North\'s Skyscape and similar designs, puts a simple inflatable or soft wing directly in your hands. On water you can combine a parawing with a foil or a surfboard for a strapless, handlebar-free downwind experience. On land and snow the same wing creates accessible entry-level kite experiences for riders who don\'t want to invest in a full bar and lines setup. Lightweight and packable, parawings travel easily.</p><ul><li><strong>Hand-held control:</strong> no bar or complicated lines — intuitive to learn</li><li><strong>Multi-discipline:</strong> works on water foils, SUPs, skis, snowboards, and land boards</li><li><strong>Packable and light:</strong> fits in a backpack for travel and crossover sessions</li></ul><p>North Skyscape parawings and similar designs from F-One are available here for all levels of rider.</p>',

  'categories/kitesurfing/protection-and-safety' => '<p>Kitesurfing is an exhilarating sport — and like all high-energy watersports, the right protection gear keeps small incidents from becoming serious ones.</p><p>Impact vests, helmets, and flotation aids are the three pillars of kitesurf protection. All three work together: a helmet protects against board strikes and shallow water impacts, an impact vest absorbs the shock of high-speed crashes and adds buoyancy, and a well-maintained safety leash ensures your kite stays manageable in an emergency. None of this kit is cumbersome — modern protection equipment is slim, flexible, and designed to be worn without noticing it.</p><ul><li><strong>Helmets:</strong> ABS hard shell and soft helmet options for different riding styles</li><li><strong>Impact vests:</strong> foam-lined vests that protect and add buoyancy</li><li><strong>Safety systems:</strong> leashes and release mechanisms to keep you in control</li></ul><p>ION, Duotone, and Cabrinha produce protection gear designed specifically for kitesurfing — not adapted from other sports.</p>',

  'categories/kitesurfing/protection-and-safety/helmets' => '<p>A kitesurf helmet is one of the most important investments you can make — board strikes and shallow water impacts happen fast, and head protection prevents the worst outcomes.</p><p>Modern kitesurf helmets are far removed from bulky ski helmets. They sit low-profile on the head, cover the temples, and use ABS hard shells or EPS foam liners to absorb impact. Half-shell designs are popular for their light weight and ventilation, while full-wrap helmets offer more coverage for wave riding and wakestyle freestyle. Ear pads help with water drainage and provide additional side impact protection.</p><ul><li><strong>ABS hard shell:</strong> tough outer layer that distributes impact force across a wide area</li><li><strong>EPS foam liner:</strong> energy-absorbing inner layer for serious impacts</li><li><strong>Adjustable fit system:</strong> dial-adjust or strap systems for a secure, comfortable fit</li></ul><p>ION, Duotone, and Cabrinha helmets are built to kitesurf-specific standards — prioritising low weight and water management.</p>',

  'categories/kitesurfing/protection-and-safety/life-jackets' => '<p>Kitesurf impact vests and life jackets provide buoyancy and impact protection in one piece of kit — particularly important in offshore conditions, waves, or when riding far from shore.</p><p>CE-rated impact vests provide 50N of buoyancy — enough to support a resting adult face-up in calm water. They also absorb the shock of high-speed water entry after big crashes, protecting ribs and internal organs. Watersport-specific vests are cut short at the waist to work with a kite harness — standard sailing life jackets interfere with harness operation and are not suitable for kitesurfing.</p><ul><li><strong>50N buoyancy:</strong> CE-certified rating to support a resting adult</li><li><strong>Short-cut design:</strong> works over or under a kite waist harness without interference</li><li><strong>Impact foam panels:</strong> front and back foam absorbs crash energy</li></ul><p>ION and Duotone life vests are designed to layer correctly with their harness ranges for full protection.</p>',

  'categories/kitesurfing/protection-and-safety/vests' => '<p>Impact protection vests for kitesurfing shield your core against hard water landings, board strikes, and the accumulated bruising of an active session in powered conditions.</p><p>Even without the buoyancy rating of a full life jacket, a well-designed impact vest makes a real difference to how your body feels after a heavy session. Segmented foam panels flex with your body through turns and jumps, then compress to absorb impact energy when you need them to. Neoprene backs add warmth as a bonus in cooler conditions, and slim construction means the vest disappears under a harness.</p><ul><li><strong>Segmented foam panels:</strong> flex freely during riding, protect on impact</li><li><strong>Slim profile:</strong> disappears under a harness without bulk</li><li><strong>Neoprene back panel:</strong> adds core warmth on cooler water days</li></ul><p>ION impact vests are a benchmark product in kitesurf protection — worn by athletes across every discipline from freestyle to big-air.</p>',

  'categories/sup-board/isup-packages' => '<p>An inflatable SUP complete package gives you everything you need to get on the water in one box — board, paddle, pump, leash, and carry bag, ready to go from day one.</p><p>Complete iSUP packages remove all the guesswork from buying your first paddleboard. The board, paddle, and pump are matched by the manufacturer and priced as a bundle that represents genuine savings over buying components separately. For families, travellers, and beginners, a complete package from a trusted brand offers the fastest path from purchase to first paddle stroke. All-round shapes in the 10\'6"–11\' range work well across flat water, light surf, and fitness paddling.</p><ul><li><strong>Board included:</strong> all-round inflatable shapes suitable for most paddlers and conditions</li><li><strong>Adjustable paddle:</strong> fibreglass or aluminium shaft adjustable for multiple heights</li><li><strong>Hand pump and bag:</strong> everything for inflation, transport, and storage</li></ul><p>Starboard and Naish complete packages are a strong starting point — two brands that take SUP seriously at every price point.</p>',

  'categories/sup-board/sup-accessories' => '<p>The right SUP accessories extend what you can do with your paddleboard — from better fins and leashes to dry bags, board locks, and roof rack systems.</p><p>Once you have a board and paddle, the accessories category fills in everything else: ankle leashes for safety, waterproof bags for keys and valuables, fin systems for different conditions, board locks for security, and care products to extend the life of your investment. Touring SUP paddlers add deck bags and hydration systems for longer expeditions, while fitness paddlers focus on quality leashes and fin setups for clean tracking.</p><ul><li><strong>Leashes:</strong> ankle and coiled options for flat water, surf, and river paddling</li><li><strong>Dry bags:</strong> waterproof storage for phones, keys, and valuables</li><li><strong>Care and maintenance:</strong> repair kits, cleaning products, and storage accessories</li></ul><p>Starboard, Naish, and ION all produce well-designed SUP accessories to complement their board ranges.</p>',

  'categories/sup-board/sup-accessories/sup-fins' => '<p>SUP fins are one of the most impactful and overlooked upgrades you can make — the right fin setup transforms how your board tracks, turns, and feels underfoot.</p><p>A single large centre fin gives maximum straight-line tracking for flat water touring and fitness paddling. A thruster setup with a centre fin and two side fins increases manoeuvrability for surfing and mixed-condition paddling. Fin size, template, and material (plastic, fibreglass, or carbon) all affect performance. US Box fins are the most common fitment across inflatable and hard boards, offering a wide aftermarket selection.</p><ul><li><strong>US Box fins:</strong> the most widely compatible fitment across brands and board types</li><li><strong>Single fin:</strong> maximum tracking efficiency for flat water touring and racing</li><li><strong>Thruster and 2+1 setups:</strong> improved manoeuvrability for wave and mixed-use paddling</li></ul><p>Starboard and Naish board-matched fins are available alongside a broad aftermarket selection for upgraders.</p>',

  'categories/sup-board/sup-inflatable-boards' => '<p>Inflatable SUP boards have made stand-up paddleboarding genuinely accessible — they store in a bag, travel on planes, and inflate to a rigid ride in under ten minutes.</p><p>Modern drop-stitch construction with dual-layer PVC delivers a board stiff enough to rival entry-level hard boards in most paddling conditions. All-round shapes (10\'–11\') suit beginners and versatile use across flat water, light surf, and fitness paddling. Touring shapes are longer and narrower for efficiency on longer distances. Race boards push performance further with minimal volume and hard rails for maximum speed. For most paddlers, an all-round iSUP is the right starting point.</p><ul><li><strong>Dual-layer PVC:</strong> drop-stitch construction for rigidity and durability</li><li><strong>All-round shapes:</strong> 10\'–11\' boards for beginners and recreational paddlers</li><li><strong>Touring and race options:</strong> longer, narrower shapes for performance paddling</li></ul><p>Starboard and Naish inflatable boards represent the upper end of iSUP construction quality — built to last and perform.</p>',

  'categories/sup-board/sup-paddles' => '<p>A quality SUP paddle makes more difference to your session than almost any other single upgrade — the right shaft material, blade size, and fit transforms every stroke.</p><p>Aluminium adjustable paddles are the starting point for beginners and casual paddlers — affordable and durable. Fibreglass shafts save meaningful weight and reduce arm fatigue on longer sessions. Carbon paddles are the choice for performance paddlers and racers: rigid, extremely light, and efficient enough to noticeably increase cadence and reduce tiredness. Blade size should be matched to your build and paddling style — smaller blades for faster, higher cadence; larger blades for more powerful, slower strokes.</p><ul><li><strong>Aluminium paddles:</strong> affordable, adjustable, and robust for beginners</li><li><strong>Fibreglass shafts:</strong> significant weight saving over aluminium for regular paddlers</li><li><strong>Carbon paddles:</strong> maximum performance with minimal swing weight for racing and touring</li></ul><p>Starboard, Naish, and NeilPryde all produce excellent SUP paddles spanning every level of the sport.</p>'
}

descriptions.each do |permalink, html|
  taxon = Spree::Taxon.find_by(permalink: permalink)
  next unless taxon
  taxon.description = html
  taxon.save!
  print '.'
end
puts "\nDone: #{descriptions.count} descriptions updated"
