source 'https://rubygems.org'

ruby '~> 3.3'

gem 'rails', '~> 7.2'
gem 'sqlite3', '~> 2.0'
gem 'puma', '~> 6.0'
gem 'rqrcode', '~> 2.2'
gem 'prawn', '~> 2.5'
gem 'image_processing', '~> 1.2'
gem 'twilio-ruby', '~> 7.0'
gem 'jbuilder', '~> 2.12'
gem 'rack-cors', '~> 2.0'
gem 'bcrypt', '~> 3.1'
gem 'dotenv-rails', '~> 3.0'

group :development, :test do
  gem 'debug', platforms: %i[mri windows]
end
